In [1]:
import numpy as np
import random

# -----------------------------
# Simple GridWorld Environment
# -----------------------------
class GridWorld:
    def __init__(self, size=4):
        self.size = size
        self.start = (0, 0)
        self.goal = (size - 1, size - 1)
        self.reset()

    def reset(self):
        self.pos = self.start
        return self.pos

    def step(self, action):
        x, y = self.pos

        if action == 0:   # up
            x = max(0, x - 1)
        elif action == 1: # down
            x = min(self.size - 1, x + 1)
        elif action == 2: # left
            y = max(0, y - 1)
        elif action == 3: # right
            y = min(self.size - 1, y + 1)

        self.pos = (x, y)

        # Reward
        if self.pos == self.goal:
            return self.pos, 1, True  # reached goal
        else:
            return self.pos, 0, False  # no reward

# -----------------------------
# Q-Learning Algorithm
# -----------------------------
env = GridWorld(size=4)

# Q-table: 4x4 grid with 4 actions each
Q = np.zeros((4, 4, 4))

alpha = 0.1      # learning rate
gamma = 0.9      # discount factor
epsilon = 0.3    # exploration probability
episodes = 2000

for _ in range(episodes):
    state = env.reset()
    done = False

    while not done:
        x, y = state

        # Epsilon-greedy action selection
        if random.random() < epsilon:
            action = random.choice([0, 1, 2, 3])  # explore
        else:
            action = np.argmax(Q[x, y])           # exploit

        next_state, reward, done = env.step(action)
        nx, ny = next_state

        # Q-learning update rule
        Q[x, y, action] = Q[x, y, action] + alpha * (
            reward + gamma * np.max(Q[nx, ny]) - Q[x, y, action]
        )

        state = next_state

# -----------------------------
# Test the trained agent
# -----------------------------
state = env.reset()
done = False
path = [state]

print("Learned Q-values:")
print(Q)

while not done:
    x, y = state
    action = np.argmax(Q[x, y])
    state, reward, done = env.step(action)
    path.append(state)

print("\nPath taken by the agent:")
print(path)


Learned Q-values:
[[[0.53144099 0.59049    0.531441   0.59049   ]
  [0.59049    0.65609999 0.53144099 0.6561    ]
  [0.6561     0.729      0.59049    0.7289915 ]
  [0.71143357 0.81       0.65609962 0.69699381]]

 [[0.43483013 0.28806923 0.45728142 0.6561    ]
  [0.58981015 0.57633664 0.58044759 0.729     ]
  [0.6561     0.80999996 0.6561     0.81      ]
  [0.7289997  0.9        0.729      0.81      ]]

 [[0.20304748 0.00450059 0.08093431 0.50501511]
  [0.65598699 0.07681583 0.1070297  0.55227136]
  [0.68738667 0.51823834 0.54716547 0.9       ]
  [0.80999997 1.         0.80999996 0.89999999]]

 [[0.07298894 0.         0.         0.        ]
  [0.36011431 0.01692739 0.         0.04113785]
  [0.72926486 0.         0.08061395 0.1       ]
  [0.         0.         0.         0.        ]]]

Path taken by the agent:
[(0, 0), (0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 3)]
